### PR TITLE
cgroup2: Add Kill method

### PR DESCRIPTION
**Pull request by dcantah**
Fixes: https://github.com/kata-containers/cgroups-rs/issues/98

Add a Kill method for cgroups v2. This uses the new functionality in [kernels 5.14+](https://lwn.net/Articles/855924/) where writing to a cgroup.kill file will send a SIGKILL to every process running in the cgroup. This would be useful for kata to avoid the freezing -> manually sending SIGKILL -> thawing process it does currently (same thing runc does at the moment).

(Please nitpick Rust idioms, don't write this often :) )

### CODE REVIEW

**Comment by Tim-Zhang** [comment]
@liubin PTAL

**Comment by liubin** [comment]
Thanks, @dcantah.

Do you mean here https://github.com/kata-containers/kata-containers/blob/ec18368aba82dcf50db087a8982d3c4935110e73/src/tools/runk/libcontainer/src/container.rs#L114-L120  by saying `freezing -> manually sending SIGKILL -> thawing process it does currently` or otherwhere?

**Comment by dcantah** [comment]
@liubin Couple spots that I saw:

1. https://github.com/kata-containers/kata-containers/blob/main/src/agent/rustjail/src/container.rs#L1122-L1130
2. https://github.com/kata-containers/kata-containers/blob/67f0fd505dc55d5913dded0fdda442575c765788/src/agent/src/rpc.rs#L424-L455

**Comment by liubin** [comment]
@dcantah a clippy warning:
>   --> tests/cgroup.rs:53:36
   |
53 |         assert_eq!(cg_procs.len(), 1 as usize);
   |                                    ^^^^^^^^^^ help: try: `1_usize`
   |


/ccc @yaoyinnan

**Comment by dcantah** [comment]
@liubin Will fix!

**Comment by dcantah** [comment]
@liubin Surprised it didn't seem to whine about any of https://github.com/kata-containers/cgroups-rs/pull/100. I also didn't have that lint locally, but I've changed it

**Review by liubin — APPROVED** [review]

**Comment by dcantah** [comment]
@liubin Curious if we could get a tag of this after this is checked in so we can pull this into the main kata-containers repo

**Comment by liubin** [comment]
@dcantah: we will create a new release after this PR has been merged.

**Review by Tim-Zhang — APPROVED** [review]

**Comment by Tim-Zhang** [comment]
LGTM, thanks @dcantah

**Comment by Tim-Zhang** [comment]
@dcantah This patch has been released in version [0.2.12](https://crates.io/crates/cgroups-rs/0.2.12)

**Pull request merged**
