### PR TITLE
make musl cgroupv2 identifying same as other target_envs

### PR DESCRIPTION
**Pull request by nrxus**
I've been noticing an issue where creating a cgroup instance with an auto hierarchy fails and the error seems to come from: https://github.com/kata-containers/cgroups-rs/blob/8d29c194e38e5aed419384c07fd9ebf6ad39966c/src/cgroup.rs#L556-L560
.I believe this is because `cgroups-rs` thinks that the machine is using cgroup v2 where it isn't. This is happening at a customer site so I can't be sure 100% but we do compile all of our binaries with `musl` as the target as we want static builds. The system is an older aws endpoint with a 4.14 kernel so I'd assume it's using a hybrid cgroup (where systemd makes a fake unified cgroup but it's still cgroup v1 in reality) instead of a pure cgroup v2 system so that may be where the musl specific cgroupv2 check fails. I think we can avoid this musl specifc code now that the crate is using v0.25 of `nix` as the needed constant was added in this version: https://github.com/nix-rust/nix/commit/23f1787d3b6c2e71f7afa398dac9050f69306e48

This PR just removes the cfg gates so that musl targets hit the same code as other targets. 

I also considered updating `nix` while i was at it since it is a couple of versions behind but I wasn't sure what your policy was for upgrading crates that cause an MSRV bump.

### CODE REVIEW

**Comment by Tim-Zhang** [comment]
@liubin I'm not familiar with this so please take a look at this.

**Review by liubin — APPROVED** [review]
@nrxus Now `nix` is 0.25.0, so it could compile.

**Comment by liubin** [comment]
Close and reopen to trigger the CI.

**Comment by Tim-Zhang** [comment]
@nrxus CI was failed, you can fix it follow the error message, thanks

**Comment by nrxus** [comment]
@Tim-Zhang I have fixed the commit message to match the expectations from CI (as per the contributing guidelines)

**Review by Tim-Zhang — APPROVED** [review]
LGTM, thanks @nrxus

**Pull request merged**
