### PR TITLE
clippy: Fix clippy version 0.1.60

### PR DESCRIPTION
**Pull request by flxo**
Fix clippy lints from clippy 0.1.60 (7737e0b 2022-04-04).

### CODE REVIEW

**Review by jodh-intel — APPROVED** [review]
Thanks @flxo.

lgtm

**Review by jodh-intel — APPROVED** [review]
Thanks @flxo.

lgtm

**Review by Tim-Zhang — APPROVED** [review]
LGTM thanks @flxo

**Pull request merged**
